apiVersion: v1
kind: Service
metadata:
  name: mci-app-service
spec:
  type: LoadBalancer 	# default
  ports:
    - nodePort: 30004	# server/localhost port exposed
      port: 8001 	# service port exposed
      targetPort: 8001	# exposed container port
  selector:
    object: mci_pod
