apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  ports:
    - nodePort: 30006
      port: 5432  # service port exposed
      targetPort: 5432  # exposed container port
  selector:
    object: pg_pod